In [1]:
#Problem 1

import numpy as np 


#Transition matrix
A = np.array([[0.03,0.19,0.27,0.51],[0.24,0.23,0.33,0.20],[0.21,0.42,0.19,0.18],[0.22,0.34,0.08,0.36]])

#Steady state vector/Stationary probability
#stat_prob_0 = np.array([0.19,0.30,0.21,0.30])


#Power method
def power_method(A, iterations, init_vec):

    A = A.T
    #Converge Transition matrix
    for i in range(iterations):
        AA = np.linalg.matrix_power(A,i)
        AAA = AA@init_vec


    return AAA


# power_method(A, 5)



In [2]:
#Problem 2_a

init_vec_a = np.array([0,1/3,1/3,1/3])
init_vec_b = np.array([0,1/4,1/4,1/4,1/4])

H_a = np.array([[0,1/3,1/3,1/3],[0,0,1/2,1/2],[1,0,0,0],[1/2,0,1/2,0]])
H_b = np.array([[0,1,0,0,0],[1,0,0,0,0],[0,0,0,1,0],[0,0,1,0,0],[0,0,1/2,1/2,0]])

alpha = 0.85


def google_mat(alpha, S):
    e = np.ones(len(S))
    E = 1/len(S)*np.outer(e,e)
    G = alpha*S + (1-alpha)*E
    return G

G_a = google_mat(0.85,H_a)
G_b = google_mat(0.85,H_b)







print('-------Raw Trans Matrix A--------')
print(power_method(H_a, 100, init_vec_a))
print('-------Raw Trans Matrix B--------')
print(power_method(H_b, 100, init_vec_b))
print('--------Google Matrix A---------')
print(power_method(G_a, 100, init_vec_a))
print('--------Google Matrix B---------')
print(power_method(G_b, 100, init_vec_b))


-------Raw Trans Matrix A--------
[ 0.38709677  0.12903226  0.29032258  0.19354839]
-------Raw Trans Matrix B--------
[ 0.25   0.     0.375  0.375  0.   ]
--------Google Matrix A---------
[ 0.36815068  0.14180936  0.28796163  0.20207834]
--------Google Matrix B---------
[ 0.20000001  0.19999998  0.28500001  0.28500001  0.03      ]


In [3]:
#Problem 2_b
print('-------Raw Trans Matrix 2A--------')
H_2a = np.array([[0,1/3,1/3,1/3,0],[0,0,1/2,1/2,0],[1/2,0,0,0,1/2],[1/2,0,1/2,0,0],[0,0,1,0,0]])
G_2a = alpha*H_2a + (1 - alpha)*1/len(H_2a[0])
print(power_method(H_2a, 100, init_vec_b))
print('--------Google Matrix 2A---------')
print(power_method(G_2a, 100, init_vec_b))


-------Raw Trans Matrix 2A--------
[ 0.24489796  0.08163265  0.36734694  0.12244898  0.18367347]
--------Google Matrix 2A---------
[ 0.23714058  0.09718983  0.34889409  0.13849551  0.17827999]


![Title](img/Trans.png)

In [4]:
import numpy as np

#Problem 2_b

#Transition Matrix
init_vec_tromso = np.array([1/2,1/2,0])
print('--------Tromsø transition matrix---------')
H_tromso = np.array([[0,1/2,1/2],[1/4,1/2,1/4],[1/4,1/4,1/2]])
G_troms = google_mat(0.85,H_tromso)
print(H_tromso)


print('--------Ranked---------')
print('{:<15} {:<12} {}'.format('Good day %','Snow %', 'Rain %'))
print(power_method(H_tromso, 100, init_vec_tromso))
print(power_method(G_troms, 100, init_vec_tromso))


--------Tromsø transition matrix---------
[[ 0.    0.5   0.5 ]
 [ 0.25  0.5   0.25]
 [ 0.25  0.25  0.5 ]]
--------Ranked---------
Good day %      Snow %       Rain %
[ 0.2  0.4  0.4]
[ 0.21649485  0.39175258  0.39175258]
